import { Fraunces } from 'next/font/google';
import './globals.css';

const fraunces = Fraunces({
  weight: ['600', '700'],
  subsets: ['latin'],
  variable: '--font-fraunces',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={fraunces.variable}>{children}</body>
    </html>
  );
}
